plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.3.0'
}

group 'xyz.atsumeru.api'
version '2.0'

repositories {
    mavenCentral()
}

dependencies {
    // RxJava 2
    implementation 'io.reactivex.rxjava2:rxjava:2.2.21'

    // Okhttp 3
    implementation 'com.squareup.okhttp3:okhttp:5.3.2'
    implementation 'com.squareup.okhttp3:logging-interceptor:5.3.2'

    // Retrofit 2
    implementation 'com.squareup.retrofit2:retrofit:3.0.0'
    implementation 'com.squareup.retrofit2:converter-gson:3.0.0'
    implementation "com.squareup.retrofit2:adapter-rxjava2:3.0.0"

    // Gson
    implementation 'com.google.code.gson:gson:2.13.2'
}

jar {
    manifest {
        attributes 'Implementation-Title': 'Atsumeru API Library',
                'Implementation-Version': version,
                'Built-By': 'Atsumeru.xyz'
    }
}